source  'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'AVTVObject' do
  pod 'ATRefresh_Swift',:git => 'https://github.com/tianya2416/ATRefresh_Swift.git'
  pod 'ATKit_Swift'
  pod 'Moya'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Hue'
  pod 'Kingfisher'
  pod 'MGJRouter_Swift'
  
  
  pod 'FDFullscreenPopGesture'
  pod 'FMDB'
  pod 'SVProgressHUD'
  pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
  pod 'VTMagic',:git => 'https://github.com/tianya2416/VTMagicMacro.git'


end

